CREATE TABLE W_USER (
  ID           VARCHAR(40) NOT NULL,
  USERNAME     VARCHAR(20) NOT NULL,
  PASSWORD     VARCHAR(20) NOT NULL,
  NAME         VARCHAR(20) NOT NULL,
  REGISTERDATE DATETIME   NOT NULL
);
